### ISSUE TITLE
Using CAS as the only authentication mechanism. 

### ISSUE THREAD

**Issue by ircerv** [jgribonvald/demo-spring-cas-angular#1]
I tried your demo-spring-cas-angular project with my CAS instance and I have one question which you may be able to answer. In this example I can successfully authenticate against my CAS, it redirects me all right but as far as I can see I'm still not able to browse that part of the app that requires authentication. For example after authenticating in CAS I can't browse metrics or logs. All I get when trying is Unauthorized. Did you try to overcome this and use CAS as the only authentication mechanism for entire application? Is it possible?

**Comment by jgribonvald** [comment]
For these accesses you need admin rights, (see the security filter on path /health /metrics, they are filtered on ADMIN rights) see more on spring-security roles configuration to map to the account you used.
